# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseClass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'PGFramework', '~> 1.2.4'
  pod 'Alamofire', '~> 4.9.1'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  # Pods for FireBaseClass

end
